litellm:
  model: qwen3:4b
  url: str
  custom_llm_provider: str = None


mem0:
  vector_store:
    provider: qdrant
    url: http://localhost:11434

  llm:
    provider: ollama
    model: qwen3:4b
    url: http://localhost:11434

  embedder:
    provider: ollama
    model: snowflake-artic-embed2:latest
    url: http://localhost:11434

  graph_store:
    provider: neo4j
    url: None
    username: None
    password: None
