[project]
name = "agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mem0ai>=0.1.109",
    "openai-agents[litellm]>=0.0.18",
]
