# mem0.yaml

# Main config for running mem0 with everything local
core:
  data_dir: ./mem0_data  # Local directory for storage
  server:
    host: 127.0.0.1
    port: 8080
    cors: true  # Set false if not exposing via browser

embedding:
  provider: huggingface
  model: sentence-transformers/all-MiniLM-L6-v2  # Or any local model you prefer
  device: cpu  # or cuda if GPU available

vector_store:
  provider: faiss
  index_file: ./mem0_data/faiss_index.index

storage:
  provider: local
  documents_dir: ./mem0_data/documents
  metadata_file: ./mem0_data/metadata.json

database:
  provider: sqlite
  db_path: ./mem0_data/mem0.db

logging:
  level: info  # Or debug for more detailed output
